server:
  port: ${PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: umas-core-service

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BROKERS:localhost:29092}
      group-id: umas-core-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "co.cetad.umas.core.domain.model.vo"
    producer:
      bootstrap-servers: ${KAFKA_BROKERS:localhost:29092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

kafka:
  topics:
    telemetry: ugcs.drone.telemetry
    events: ugcs.drone.events
    commands: ugcs.drone.execute
    vehicle-status: ugcs.drone.vehicle.status
    route-status: ugcs.drone.route.status

ugcs:
  server:
    host: ${UGCS_HOST:192.168.100.243}
    port: ${UGCS_PORT:3334}
  credentials:
    login: ${UGCS_LOGIN:admin}
    password: ${UGCS_PASS:admin}
  reconnect:
    enabled: true
    initial-delay: 5000
    max-delay: 60000
    multiplier: 2.0