server:
  port: ${PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: umas-core-service

kafka:
  topics:
    telemetry: ugcs.drone.telemetry
    events: ugcs.drone.events
    commands: ugcs.drone.execute
    vehicle-status: ugcs.drone.vehicle.status
    route-status: ugcs.drone.route.status

ugcs:
  server:
    host: ${UGCS_HOST}
    port: ${UGCS_PORT}
  credentials:
    login: ${UGCS_LOGIN}
    password: ${UGCS_PASS}
  reconnect:
    enabled: true
    initial-delay: 5000
    max-delay: 60000
    multiplier: 2.0